server:
  port: 8080

spring:
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:file:~/dev/temp/h2db/rememberme;
#    username: sa
#    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sogang_ari?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: nz1202nz
#
#
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    generate-ddl: true
#    hibernate:
#      ddl-auto: create-drop
  jpa:
    show_sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create