server:
  port: 8080

spring:
  jpa:
    open-in-view: true
    show_sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        enable_lazy_load_no_trans: true
    generate-ddl: false
    hibernate:
      ddl-auto: none # Create -> Update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sogang_ari
    username:
    password:
    initialization-mode: never
  mail:
    host: smtp.gmail.com
    port: 587
    username: sogangari
    password: 
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  redis:
    host: 127.0.0.1
    port: 6379

  logo:
    path: C:\\Users\\Administrator\\Desktop     # 원격용
#    path: C:\\Users\\9997i\\Desktop\\work_space\\test      # 로컬용
    folder: \\logoes\\

