server:
  port: 8080

spring:
  jpa:
    show_sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: none # Create -> Update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sogang_ari
    username: howoo
    password:

  mail:
    host: smtp.gmail.com
    port: 587
    username: sogangari
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  redis:
    host: 127.0.0.1
    port: 6379


